kind: Deployment
apiVersion: apps/v1
metadata:
  name: bench
  labels:
    app: bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench
  template:
    metadata:
      labels:
        app: bench
    spec:
      containers:
        - name: cloud-benchmark
          image: ghcr.io/pbochynski/cloud-benchmark:0.0.5
          resources:
            limits:
              memory: 400M
            requests:
              cpu: 1000m
              memory: 200M
---
kind: Service
apiVersion: v1
metadata:
  name: bench
  labels:
    app: bench
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: bench
  type: ClusterIP
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bench
  labels:
    app.kubernetes.io/name: bench
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods:
        - GET
      accessStrategies:
        - handler: allow
  host: bench
  service:
    name: bench
    port: 3000
