kind: Deployment
apiVersion: apps/v1
metadata:
  name: bench
  labels:
    app: bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench
  template:
    metadata:
      labels:
        app: bench
    spec:
      containers:
      - name: cloud-benchmark
        image: ghcr.io/pbochynski/cloud-benchmark:latest
        resources:
          limits:
            memory: 400M
        env:
        - name: DATA_ROOT
          value: /data
        volumeMounts:
        - name: shared-fs
          mountPath: /data
      volumes:
      - name: shared-fs
        persistentVolumeClaim:
          claimName: efs-claim
          readOnly: false
---
kind: Service
apiVersion: v1
metadata:
  name: bench
  labels:
    app: bench
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: bench
  type: ClusterIP
