apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bench
  labels:
    app: bench
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bench
  template:
    metadata:
      labels:
        app: bench
    spec:
      containers:
      - name: cloud-benchmark
        image: ghcr.io/pbochynski/cloud-benchmark:main
        resources:
          limits:
            memory: 400M
          requests:
            cpu: 1000m
            memory: 200M
        env:
        - name: DATA_FOLDER
          value: /data
        volumeMounts:
        - name: shared-fs
          mountPath: /data
      volumes:
      - name: shared-fs
        persistentVolumeClaim:
          claimName: cephfs-pvc
          readOnly: false
---
kind: Service
apiVersion: v1
metadata:
  name: bench
  labels:
    app: bench
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: bench
  type: ClusterIP
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bench
  labels:
    app.kubernetes.io/name: bench
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods:
        - GET
      accessStrategies:
        - handler: allow
  host: bench
  service:
    name: bench
    port: 3000
