---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: os-manila-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-manila-nfs
  resources:
    requests:
      storage: 5Gi
